### ISSUE TITLE
[Supernova] add "Scheduled Maintenance" feature for creating predefined and prescheduled silences

### ISSUE THREAD

**Issue by edda** [sapcc/juno#398]

**Comment by TilmanHaupt** [comment]
Issues I am facing so far

There is no Juno-Component for the Date so far, which would be good for the Form.

I the past Scheduled-Silence form there was no „Created By“ in the Call, also my formState is inherently different then the old JSON, which is sent in the old call. At this point I am converting the formState to a new JSON before sending. (e.g. Fixed and Editable Labels > LabelValues). Solution Alternatives: Handle it the old way. / Change Backend.

I am not able to get the YAML from: „ /api/support/silence-templates“, to don’t use anymore fake Templates.

I am not able to send the silences to a real server alone - because, dangerous as a beginner.

Bug: When to Options in the Template-Select have the same name, although they don’t have the same id (generated through index in the map) they are both seem to be selected
